---
version: '2'
services:
  es:
    image: elasticsearch
    networks:
      test:
        ipv4_address: 10.5.0.10
  logstash:
    image: logstash
    depends_on:
      - es
    volumes:
      - ./logstash/logstash.conf:/config-dir/logstash.conf
    links:
      - es:elasticsearch
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - es
    networks:
      test:
        ipv4_address: 10.5.0.11
  kibana:
    image: kibana
    links:
      - es:elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - es
      - logstash
    networks:
      test:
        ipv4_address: 10.5.0.12

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
